name: Lint, Build, and Test Libauth
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, latest]
        runner_index: [0, 1, 2, 3]
        runners_per_version: [4]
    name: Test Node ${{ matrix.node }} (${{ matrix.runner_index }}/${{ matrix.runners_per_version }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: yarn test:unit
        env:
          CI_NODE_INDEX: ${{ matrix.runner_index }}
          CI_NODE_TOTAL: ${{ matrix.runners_per_version }}
      - run: yarn cov:lcov
      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  check-policies:
    runs-on: ubuntu-latest
    name: Check Policies
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build
      - run: yarn test:policies
